server:
  port: 8084

spring:
  application:
    name: user-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: ruang
    password: ruang
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
