server:
  port: 8082

app:
  redis:
    enabled: true

spring:
  application:
    name: coupon-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/coupon_db
    username: ruang
    password: ruang
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 250000
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
