server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/api/orders/**
          filters:
            - RewritePath=/api/orders(?<segment>/?.*), /orders${segment}

        - id: balance-service
          uri: http://balance-service:8081
          predicates:
            - Path=/api/balances/**
          filters:
            - RewritePath=/api/balances/(?<segment>.*), /balances${segment}

        - id: coupon-service
          uri: http://coupon-service:8082
          predicates:
            - Path=/api/coupons/**
          filters:
            - RewritePath=/api/coupons/(?<segment>.*), /coupons${segment}

        - id: product-service
          uri: http://product-service:8083
          predicates:
            - Path=/api/products/**
          filters:
            - RewritePath=/api/products/(?<segment>.*), /products${segment}

        - id: user-service
          uri: http://user-service:8084
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /users${segment}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always





