server:
  port: 8080

app:
  redis:
    enabled: true

spring:
  application:
    name: order-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: ruang
    password: ruang
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 250000
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    acks: 1
    retries: 3
    properties:
      enable.idempotence: true
  consumer:
    group-id: order-consumer-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.trusted.packages: com.hhplus.ecommerce.common.event
    auto-offset-reset: earliest
    enable-auto-commit: true
    auto-commit-interval: 1000

services:
  balance:
    url: http://localhost:8081
  coupon:
    url: http://localhost:8082
  product:
    url: http://localhost:8083
  user:
    url: http://localhost:8084
