server:
  port: 8080

spring:
  application:
    name: order-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://order-service:3306/order_db
    username: ruang
    password: ruang
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 250000
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  balance:
    url: http://balance-service:8081
  coupon:
    url: http://coupon-service:8082
  product:
    url: http://product-service:8083
  user:
    url: http://user-service:8084

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
