server:
  port: 8080

spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-order:3306/order_db}
    username: ${SPRING_DATASOURCE_USERNAME:ruang}
    password: ${SPRING_DATASOURCE_PASSWORD:ruang}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 250000
      connection-timeout: 5000
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2

services:
  balance:
    url: ${SERVICES_BALANCE_URL:http://balance-service:8081}
  coupon:
    url: ${SERVICES_COUPON_URL:http://coupon-service:8082}
  product:
    url: ${SERVICES_PRODUCT_URL:http://product-service:8083}
  user:
    url: ${SERVICES_USER_URL:http://user-service:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.hhplus.ecommerce: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"