server:
  port: 8080

spring:
  application:
    name: order-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: ruang
    password: ruang
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  balance:
    url: http://localhost:8081
  coupon:
    url: http://localhost:8082
  product:
    url: http://localhost:8083
  user:
    url: http://localhost:8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
