server:
  port: 8083

spring:
  application:
    name: product-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://product-service:3306/product_db
    username: ruang
    password: ruang
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 250000
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
